[package]
name = "biceps"
version = "0.0.1"
entrypoint = "lib.typ"
authors = ["Julien Scholz <https://www.julien-scholz.dev>"]
license = "MIT"
description = "Layout algorithm for CSS-style flex-wrap behavior. 💪"
